name: Notifier Microservices CI with ESO for secret mgmt
on:
  pull_request:
    branches: ['main','develop/*']
    types: [opened, synchronize, reopened]

# Both workflows should have the same concurrency group
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  # Cancel any in-progress runs in the same group and runs only the latest commit

jobs:
  notifier-service-ci:
    uses: cloudhein/workflows/.github/workflows/common-jobs.yaml@87209d4836301115ead06edd2d41a39a68a61f79
    with:
      working-directory: 'cmd/api'
      go-version: ">=1.22"
      binary-name: 'notifier' # This maps to -o notifier
      sonar-project-key: cloudhein_notifier
      sonar-organization: cloudhein
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}

  notifier-deploy-service:
    if: github.ref == 'refs/heads/main' || (github.event_name == 'pull_request' && github.base_ref == 'main')
    needs: notifier-service-ci
    uses: cloudhein/workflows/.github/workflows/deploy-jobs.yaml@87209d4836301115ead06edd2d41a39a68a61f79
    with:
      service-name: 'notifier'
      dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
      helm-repo: 'cloudhein/notifier-helm-chart'
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}